global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: maluca-proxy
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - maluca-proxy:8080
        labels:
          instance_group: proxy

  - job_name: maluca-proxy-multi
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - maluca-proxy-1:8080
          - maluca-proxy-2:8080
        labels:
          instance_group: proxy-multi
