global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'maluca-proxy'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['maluca-proxy:8080']
    scrape_interval: 5s   # faster scrape for demo visibility
